### ISSUE TITLE
Apprendre à developper

### ISSUE THREAD

**Issue by DieuKoukiFactori** [DevSupDeveloper/Site-DevSupport#18]
http://openclassrooms.com/
http://openclassrooms.com/
http://openclassrooms.com/
http://openclassrooms.com/
http://openclassrooms.com/
http://openclassrooms.com/
http://openclassrooms.com/
http://openclassrooms.com/
http://openclassrooms.com/
http://openclassrooms.com/
http://openclassrooms.com/
http://openclassrooms.com/
http://openclassrooms.com/
http://openclassrooms.com/
http://openclassrooms.com/
http://openclassrooms.com/
http://openclassrooms.com/
http://openclassrooms.com/
http://openclassrooms.com/
http://openclassrooms.com/
http://openclassrooms.com/
http://openclassrooms.com/
http://openclassrooms.com/
http://openclassrooms.com/
http://openclassrooms.com/

**Comment by DieuKoukiFactori** [comment]
WOLA T UNE PUT

**Comment by AntoineJT** [comment]
NONMEO! TRAULé C PA BI1!
